### ISSUE TITLE
Compilation fail with libmecab under 0.98

### ISSUE THREAD

**Issue by dayflower** [lestrrat-p5/Text-MeCab#8]
Part of constants you added by hand on a9ac81c17ef763a442488b0ede8a0d3f4fd950df are not defined on libmecab below 0.98.

```
        MECAB_ONE_BEST = MECAB_ONE_BEST
        MECAB_NBEST    = MECAB_NBEST
        MECAB_PARTIAL  = MECAB_PARTIAL
        MECAB_MARGINAL_PROB = MECAB_MARGINAL_PROB
        MECAB_ALTERNATIVE = MECAB_ALTERNATIVE
        MECAB_ALL_MORPHS = MECAB_ALL_MORPHS
        MECAB_ALLOCATE_SENTENCE = MECAB_ALLOCATE_SENTENCE
```

These constants are used only for MeCab::Lattice::request_type() (described in mecab.h).
So I think they are useless for `Text::MeCab`, which does not handle `MeCab::Lattice`.

I know I have to use latest library for MeCab.  But I would appreciate it if you could remove these constants from `MeCab.xs`, that would make compilations available for libmecab 0.96-0.98.

**Comment by lestrrat** [comment]
I currently don't have tuits for this. It should be simple enough to put some #ifdef in the appropriate locations, e.g.:

```
#ifdef MECAB_ONE_BEST
     MECAB_ONE_BEST = MECAB_ONE_BEST
#endif
```

Would appreciate a p-r :)

**Comment by dayflower** [comment]
But `#ifdef` preprocessor directives are not allowed in `ALIAS` block. (ToT)

> C preprocessor directives are allowed within BOOT:, PREINIT: INIT:, CODE:, PPCODE:, POSTCALL:, and CLEANUP: blocks, as well as outside the functions.

すみません，ここから日本語で失礼します。

現在，定数は ALIAS 使った (整数定数にしか使えないという意味で) ややトリッキーな方法で実現されてますが，
(h2xs 使っても同様なロジックになるのでトリッキーはいいすぎですけど)
これを以下のように一つ一つ愚直に分解すれば，`#ifdef` を使うことができるようになります。

``` c
#ifdef MECAB_ONE_BEST
IV
MECAB_ONE_BEST()
    CODE:
        RETVAL = MECAB_ONE_BEST;
    OUTPUT:
        RETVAL

#endif
```

この形にコードを変更して pull-req 送るの，自分としては喜んでやります! なのですが，
Project owner の @lestrrat さんのご意見をお伺いしたく，という感じであります。

**Comment by lestrrat** [comment]
最初から日本語でいいんですよ！ｗ

ああ、なるほど。ALIASかー。なんかデジャブだったんだけど、こういうのにばらしちゃうのが早そう（ZMQ::LibZMQ3の自動生成ファイルより抜粋）：

```
    {
        HV *stash = gv_stashpv("ZMQ::LibZMQ3", TRUE);
#ifdef HAS_ZMQ_CTX_DESTROY
        newCONSTSUB(stash, "HAS_ZMQ_CTX_DESTROY", &PL_sv_yes);
#else
        newCONSTSUB(stash, "HAS_ZMQ_CTX_DESTROY", &PL_sv_no);
#endif
    }
```

で、これをBOOT: セクションから読み込む感じにして、これまでのconstants()を廃止、って感じで！

**Comment by dayflower** [comment]
newCONSTSUB() とか，全然知りませんでした情弱です。

既存 Issue に Pull-req のせるのまるでうまくいったことないので，別途 p-r 出します。すみません。
